### PR TITLE
Implementation of `isStream`

### PR DESCRIPTION
**Pull request by danielkarch**
I think this should work.

### CODE REVIEW

**Comment by jcranky** [comment]
What a symbol is supposed to be in that case? Also, did this change and test state?

**Comment by danielkarch** [comment]
Reading a bit about type symbols, I do not understand them enough to confidently recommend using this approach. 
But what about defining it as 
```scala
  def isStream: Boolean =
      t <:< weakTypeOf[Stream[Any, _]]
```
?

I guess we only care about the outermost type being a `Stream`, and it's covariant in its first argument, so this will work.

**Comment by danielkarch** [comment]
btw. Both would fix the tests in `TypeBuilderSpec`.

**Comment by danielkarch** [comment]
Pushed a new implementation using existential types.

**Comment by DStranger** [comment]
Hey guys, I guess I better look at existing pull requests before submitting mine. Anyway, I think implementation here should be sufficient - https://github.com/jcranky/rho/pull/8/commits/7acd876a5b58aefd303394b02c11d56ccac6f4d4

**Comment by jcranky** [comment]
thanks XD

**Pull request merged**
